name: "Auto Format Issue Title"
run-name: format issue title

on:
  issues:
    types: [opened, edited]

  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number to format manually"
        required: true
        type: string

concurrency:
  group: format-title-${{ github.event.inputs.issue_number || github.event.issue.number }}
  cancel-in-progress: true

permissions:
  issues: write

jobs:
  format_title:
    runs-on: ubuntu-latest
    # Skip only if it's an automated event AND the prefix is already present
    if: |
      github.event_name == 'workflow_dispatch' || 
      contains(github.event.issue.title, format('{0}-', vars.PROJECT_PREFIX)) == false

    steps:
      - uses: actions/checkout@v6
      - name: Format Issue Title
        uses: recursivezero/action-club/.github/actions/format-issue-title@main
        with:
          prefix: ${{ vars.PROJECT_PREFIX }}
          issue_number: ${{ github.event.inputs.issue_number }}
